### ISSUE TITLE
请问这些解码过程还有这一大堆 magicnumber 怎么得出的

### ISSUE THREAD

**Issue by Ghastlcon** [wasupandceacar/threp#3]
这 decode 和 decompress 也太神秘了，反编译得出的吗

**Comment by wasupandceacar** [comment]
magicnumber是魔数，又名文件头，具体解释自行百度
解包函数的确是反编译得到的

**Comment by Ghastlcon** [comment]
> magicnumber是魔数，又名文件头，具体解释自行百度
> 解包函数的确是反编译得到的

我的意思是比如说这些乱七八糟的offset和两次折半xor的参数是咋来的。。暴力反编译是吗，那没事了（

**Comment by wasupandceacar** [comment]
妖妖梦那个是抄皇家烈焰源码里的解包的，不过我后来发现应该也能用后面的套路解包，但懒得改了。具体可以看皇家烈焰的源码

**Comment by wasupandceacar** [comment]
其他的都是参考另外的一个repo做的，具体你可以搜下threp
