### ISSUE TITLE
建议增加获取每一面开始时的资源数的接口

### ISSUE THREAD

**Issue by CuteReimu** [wasupandceacar/threp#6]
考虑到rep是可以从任意一面开始放的，那么rep文件中一定有每一面开始时的资源数的数据。
可以参考：https://github.com/wz520/thhyl 。确实可以获得

**Comment by wasupandceacar** [comment]
可以，你可以研究下这些数据在哪，然后把接口加进来。
pr 以后我修改下测试用例再 merge
